"""add relationship with Telegram comments and Comment moderation label

Revision ID: 1319ae02238c
Revises: 3aa9b3fb02e6
Create Date: 2026-06-05 15:04:07.381460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1319ae02238c"
down_revision: Union[str, Sequence[str], None] = "3aa9b3fb02e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment_moderation_labels",
        sa.Column("vk_comment_id", sa.Uuid(), nullable=False),
    )
    op.add_column(
        "comment_moderation_labels",
        sa.Column("tg_comment_id", sa.Uuid(), nullable=False),
    )
    op.add_column(
        "comment_moderation_labels",
        sa.Column("comment_type", sa.String(), nullable=False),
    )
    op.drop_index(
        op.f("ix_comment_moderation_labels_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.create_index(
        op.f("ix_comment_moderation_labels_tg_comment_id"),
        "comment_moderation_labels",
        ["tg_comment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_comment_moderation_labels_vk_comment_id"),
        "comment_moderation_labels",
        ["vk_comment_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("comment_moderation_labels_comment_id_fkey"),
        "comment_moderation_labels",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "comment_moderation_labels", "VKComments", ["vk_comment_id"], ["id"]
    )
    op.create_foreign_key(
        None, "comment_moderation_labels", "TelegramComments", ["tg_comment_id"], ["id"]
    )
    op.drop_column("comment_moderation_labels", "comment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment_moderation_labels",
        sa.Column("comment_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        None, "comment_moderation_labels", type_="foreignkey"  # type: ignore
    )
    op.drop_constraint(
        None, "comment_moderation_labels", type_="foreignkey"  # type: ignore
    )
    op.create_foreign_key(
        op.f("comment_moderation_labels_comment_id_fkey"),
        "comment_moderation_labels",
        "VKComments",
        ["comment_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_comment_moderation_labels_vk_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.drop_index(
        op.f("ix_comment_moderation_labels_tg_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.create_index(
        op.f("ix_comment_moderation_labels_comment_id"),
        "comment_moderation_labels",
        ["comment_id"],
        unique=True,
    )
    op.drop_column("comment_moderation_labels", "comment_type")
    op.drop_column("comment_moderation_labels", "tg_comment_id")
    op.drop_column("comment_moderation_labels", "vk_comment_id")
    # ### end Alembic commands ###
