"""add telegram models

Revision ID: 3aa9b3fb02e6
Revises: a6bf92f20272
Create Date: 2026-06-02 10:15:23.430244

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3aa9b3fb02e6"
down_revision: Union[str, Sequence[str], None] = "a6bf92f20272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "TelegramPosts",
        sa.Column("group_name", sa.TEXT(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("link", sa.TEXT(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("parsed", sa.BOOLEAN(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "TelegramComments",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("author", sa.TEXT(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("author_link", sa.TEXT(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["TelegramPosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_TelegramComments_post_id"),
        "TelegramComments",
        ["post_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_TelegramComments_post_id"), table_name="TelegramComments")
    op.drop_table("TelegramComments")
    op.drop_table("TelegramPosts")
    # ### end Alembic commands ###
