"""fix names in VKPost model

Revision ID: 5db890c8112e
Revises: 49c047448c5f
Create Date: 2026-05-22 16:00:13.337185

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5db890c8112e"
down_revision: Union[str, Sequence[str], None] = "49c047448c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("VKPosts", sa.Column("comments", sa.Integer(), nullable=False))
    op.add_column("VKPosts", sa.Column("share", sa.Integer(), nullable=False))
    op.drop_column("VKPosts", "comments_count")
    op.drop_column("VKPosts", "share_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "VKPosts",
        sa.Column("share_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "VKPosts",
        sa.Column("comments_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("VKPosts", "share")
    op.drop_column("VKPosts", "comments")
    # ### end Alembic commands ###
