"""add comment moderation label model

Revision ID: 77a2bebc8b4b
Revises: 9158f471747d
Create Date: 2026-05-26 11:23:48.631148

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77a2bebc8b4b"
down_revision: Union[str, Sequence[str], None] = "9158f471747d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_moderation_labels",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.TEXT(), nullable=False),
        sa.Column("moderator_note", sa.TEXT(), nullable=True),
        sa.Column("moderator_name", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["VKComments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_moderation_labels_comment_id"),
        "comment_moderation_labels",
        ["comment_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_comment_moderation_labels_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.drop_table("comment_moderation_labels")
    # ### end Alembic commands ###
