"""add parsed field to VKPost model

Revision ID: 8006668464a6
Revises: 5db890c8112e
Create Date: 2026-05-24 11:31:52.557979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8006668464a6"
down_revision: Union[str, Sequence[str], None] = "5db890c8112e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("VKPosts", sa.Column("parsed", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("VKPosts", "parsed")
    # ### end Alembic commands ###
