"""add back populate for comments

Revision ID: 9158f471747d
Revises: 8006668464a6
Create Date: 2026-05-24 19:12:33.403411

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9158f471747d"
down_revision: Union[str, Sequence[str], None] = "8006668464a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "VKComments",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("author", sa.TEXT(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("author_link", sa.TEXT(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["VKPosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_VKComments_post_id"), "VKComments", ["post_id"], unique=False
    )
    op.add_column("VKPosts", sa.Column("comments_count", sa.Integer(), nullable=False))
    op.drop_column("VKPosts", "comments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "VKPosts",
        sa.Column("comments", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("VKPosts", "comments_count")
    op.drop_index(op.f("ix_VKComments_post_id"), table_name="VKComments")
    op.drop_table("VKComments")
    # ### end Alembic commands ###
