"""fix

Revision ID: a219ca4cae6d
Revises: 1319ae02238c
Create Date: 2026-06-05 15:08:03.836898

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a219ca4cae6d"
down_revision: Union[str, Sequence[str], None] = "1319ae02238c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_comment_moderation_labels_tg_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.drop_index(
        op.f("ix_comment_moderation_labels_vk_comment_id"),
        table_name="comment_moderation_labels",
    )
    op.create_unique_constraint(None, "comment_moderation_labels", ["tg_comment_id"])
    op.create_unique_constraint(None, "comment_moderation_labels", ["vk_comment_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comment_moderation_labels", type_="unique")  # type: ignore
    op.drop_constraint(None, "comment_moderation_labels", type_="unique")  # type: ignore
    op.create_index(
        op.f("ix_comment_moderation_labels_vk_comment_id"),
        "comment_moderation_labels",
        ["vk_comment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_comment_moderation_labels_tg_comment_id"),
        "comment_moderation_labels",
        ["tg_comment_id"],
        unique=True,
    )
    # ### end Alembic commands ###
