"""fix

Revision ID: a50d8bc6698b
Revises: a219ca4cae6d
Create Date: 2026-06-05 15:08:48.633138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50d8bc6698b"
down_revision: Union[str, Sequence[str], None] = "a219ca4cae6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment_moderation_labels",
        "vk_comment_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "comment_moderation_labels",
        "tg_comment_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment_moderation_labels",
        "tg_comment_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "comment_moderation_labels",
        "vk_comment_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
