"""remove moderator note and name from table

Revision ID: a6bf92f20272
Revises: 77a2bebc8b4b
Create Date: 2026-05-26 14:39:33.796055

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a6bf92f20272"
down_revision: Union[str, Sequence[str], None] = "cf219ca0aeba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
