"""refactor labels

Revision ID: ad7688278c8a
Revises: a50d8bc6698b
Create Date: 2026-06-07 11:14:46.143830

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad7688278c8a"
down_revision: Union[str, Sequence[str], None] = "a50d8bc6698b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_labels",
        sa.Column("comment_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["TelegramComments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
    )
    op.create_table(
        "vk_labels",
        sa.Column("comment_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["VKComments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
    )
    op.drop_table("comment_moderation_labels")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_moderation_labels",
        sa.Column("label", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("vk_comment_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("tg_comment_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("comment_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_comment_id"],
            ["TelegramComments.id"],
            name=op.f("comment_moderation_labels_tg_comment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["vk_comment_id"],
            ["VKComments.id"],
            name=op.f("comment_moderation_labels_vk_comment_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comment_moderation_labels_pkey")),
        sa.UniqueConstraint(
            "tg_comment_id",
            name=op.f("comment_moderation_labels_tg_comment_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "vk_comment_id",
            name=op.f("comment_moderation_labels_vk_comment_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("vk_labels")
    op.drop_table("telegram_labels")
    # ### end Alembic commands ###
