"""remove moderator note and name from table

Revision ID: cf219ca0aeba
Revises: 77a2bebc8b4b
Create Date: 2026-05-26 14:39:33.796055

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf219ca0aeba"
down_revision: Union[str, Sequence[str], None] = "77a2bebc8b4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comment_moderation_labels", "moderator_note")
    op.drop_column("comment_moderation_labels", "moderator_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment_moderation_labels",
        sa.Column("moderator_name", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comment_moderation_labels",
        sa.Column("moderator_note", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
